services:
  frontend:
    image: "kevinmateog/flix-frontend"
    container_name: flix-frontend
    ports:
      - "${PORT:-5173}:5173"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: production
      PORT: "5173"
      HOSTNAME: 0.0.0.0
      BACKEND: http://host.docker.internal:3000
      NEXT_PUBLIC_URL: http://localhost:5173
    restart: unless-stopped
