services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND: http://localhost:3000
        NEXT_PUBLIC_URL: http://localhost:5173
    container_name: flix-frontend
    network_mode: host
    environment:
      NODE_ENV: production
      PORT: "5173"
      HOSTNAME: 0.0.0.0
      BACKEND: http://localhost:3000
      NEXT_PUBLIC_URL: http://localhost:5173
    restart: unless-stopped
